name: github-monthly-report
on:
  workflow_dispatch:
    inputs:
      monthstart:    
        required: true
        default: '2022-xx-01'
      monthend:    
        required: true
        default: '2022-xx-31'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORG: 'chromiecraft'
  REPO: 'chromiecraft'
  API_URL_PREFIX: 'https://api.github.com'
  MONTH_START: ${{ github.event.inputs.monthstart }}
  MONTH_END: ${{ github.event.inputs.monthend }}

jobs:
  github-monthly-report:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull data from Github"
        run: source ./.github/workflows/github-issues.sh

      - name: "Send file output.txt to discord channel"
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MONTHLY_REPORT }}
        with:
          args: output.txt
