name: github-monthly-report
on:
  workflow_dispatch:
    inputs:
      monthstart:    
        required: true
        default: '2022-xx-01'
      monthend:    
        required: true
        default: '2022-xx-31'

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  ORG: 'chromiecraft'
  REPO: 'chromiecraft'
  API_URL_PREFIX: 'https://api.github.com'
  MONTH_START: ${{ github.event.inputs.monthstart }}
  MONTH_END: ${{ github.event.inputs.monthend }}
  EVENT_START: '2021-06-01'
  EVENT_END: '2022-12-31'

jobs:
  github-monthly-report:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: "Pull data from Github"
        shell: bash
        run: |
          ./apps/github-issues.sh
        
      - name: "Send file output.txt to discord channel"
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MONTHLY_REPORT }}
        with:
          args: output.txt
